version: '3.9'

services:
  auth-service:
    build: ../backend/auth-service
    image: auth-service
    ports:
      - "9070:9070"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  vault-service:
    build: ../backend/vault-service
    image: vault-service
    ports:
      - "9071:9071"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
