version: '3.9'

services:
  vigipastore:
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    image: vigipastore:latest
    ports:
      - "8080:8080"
    volumes:
      - vigipastore_data:/var/lib/postgresql/data
    container_name: vigipastore
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=vigipastore
      - APP_VERSION=1.0.0
      # - ACCESS_TOKEN_EXPIRE_MINUTES=15

volumes:
  vigipastore_data:
    external: true
