name: Infra

on:
  push:
    branches: [ main ]
    paths:
      - 'deployments/infra/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'deployments/infra/**'

jobs:
  terraform:
    runs-on: ubuntu-latest
    if: false # temporarily disable infra deployment
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: deployments/infra
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION || 'ap-southeast-1' }}
