name: CI & Deployment

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'deployments/infra/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'deployments/infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    if: false # temporarily disable build
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: Set up Node.js
        uses: actions/setup-node@v5.0.0
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci --prefix frontend/mypass-vault-app

      - name: Build frontend
        run: npm run build --prefix frontend/mypass-vault-app

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/mypass-vault-app/build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    if: false # temporarily disable deployment
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: frontend/mypass-vault-app/build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION || 'ap-southeast-1' }}

      - name: Deploy to S3
        run: aws s3 sync frontend/mypass-vault-app/build/ s3://h3yzack-my-pass-vault-app --delete

        